#!/usr/bin/env bash

# Setup defaults
# ==============
printf "Setting up dock, mouse rate, hot corners, minimze effect, and key repeat\n"
# Move dock to LHS
defaults write com.apple.dock orientation -string left

# Autohide dock
defaults write com.apple.dock autohide -bool true

# Use a medium icon size for dock icons
defaults write com.apple.dock tilesize -int 48

# Use a rapid key repeat rate
defaults write -g KeyRepeat -int 2
defaults write -g InitialKeyRepeat -int 25

# Use a fast mouse movement rate
defaults write -g com.apple.mouse.scaling -float 6.0

# Configure the bottom left hotcorner to Mission Control
defaults write com.apple.dock wvous-bl-corner -int 2
defaults write com.apple.dock wvous-bl-modifier -int 0

# Change minimize/maximize window effect
defaults write com.apple.dock mineffect -string "scale"

# Set desktop bg with m-cli
# =========================

# Clone bgs directory if it doesn’t exist
if [ ! -e "$HOME/Desktop/.bgs" ]; then
  printf "Cloning backgrounds into ~/Desktop/.bgs…\n"
  git clone https://github.com/ndmekala/bgs.git "$HOME/Desktop/.bgs"
fi

# Set the desktop background to match the season
if [[ $(brew list | grep m-cli) ]]; then
  mmdd=$(date '+%m%d' | sed 's/^0*//')
  if [[ $mmdd -lt 300 || $mmdd -ge 1200 ]]; then
    printf "Setting the winter ❄️  background…\n"
    m wallpaper "$HOME/Desktop/.bgs/winter.jpg"
  elif [[ $mmdd -ge 300 && $mmdd -lt 600 ]]; then
    printf "Setting the spring 🌱 background…\n"
    m wallpaper "$HOME/Desktop/.bgs/spring.jpg"
  elif [[ $mmdd -ge 600 && $mmdd -lt 915 ]]; then
    printf "Setting the summer 😎 background…\n"
    m wallpaper "$HOME/Desktop/.bgs/summer.jpg"
  elif [[ $mmdd -ge 915 || $mmdd -lt 1200 ]]; then
    printf "Setting the fall 🍂 background…\n"
    m wallpaper "$HOME/Desktop/.bgs/fall.jpg"
  fi
else
  printf "m-cli not installed! Skipping…\\nn"
fi


